name: Code Quality Test
on:
  pull_request:
    branches: ['master']
permissions:
  checks: write
  contents: write
jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      - name: Test Quality
        run: |
          npm install
          npm run lint
          npm run test
